CREATE DATABASE IF NOT EXISTS swift_fleet;
USE swift_fleet;

CREATE TABLE IF NOT EXISTS `user` (
  userID INT AUTO_INCREMENT PRIMARY KEY,
  fullname VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  phone VARCHAR(20),
  password VARCHAR(255) NOT NULL,
  role ENUM('manager','customer') DEFAULT 'customer'
);

CREATE TABLE IF NOT EXISTS buses (
  busID INT AUTO_INCREMENT PRIMARY KEY,
  plateNumber VARCHAR(20) NOT NULL UNIQUE,
  total_seat INT NOT NULL DEFAULT 45
);

CREATE TABLE IF NOT EXISTS `Route` (
  routeID INT AUTO_INCREMENT PRIMARY KEY,
  source VARCHAR(100) NOT NULL,
  destination VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS `schedule` (
  schID INT AUTO_INCREMENT PRIMARY KEY,
  busID INT NOT NULL,
  routeID INT NOT NULL,
  departure_time DATETIME NOT NULL,
  FOREIGN KEY (busID) REFERENCES buses(busID) ON DELETE CASCADE,
  FOREIGN KEY (routeID) REFERENCES `Route`(routeID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ticket (
  ticketID INT AUTO_INCREMENT PRIMARY KEY,
  customerName VARCHAR(100) NOT NULL,
  schID INT NOT NULL,
  seatNumber INT NOT NULL,
  FOREIGN KEY (schID) REFERENCES `schedule`(schID) ON DELETE CASCADE,
  UNIQUE KEY unique_seat (schID, seatNumber)
);